### ISSUE TITLE
First column of Table is empty on mobile

### ISSUE THREAD

**Issue by sirineJ** [sumup-oss/circuit-ui#1950] opened 2023-02-13 14:25 UTC
## Describe the bug
![Screenshot 2023-02-13 at 09 39 32](https://user-images.githubusercontent.com/112706079/218483256-b71d4b44-cc8b-42d6-9e0a-ed9af76b7bed.png)

On mobile, the first column of the table is completely empty of cells.

## Steps to reproduce

go to [circuit-ui > Table > Base](https://circuit.sumup.com/?path=/docs/components-table--base) story, select 'Small mobile' viewport. 

## Expected behavior

The cells of the first row should appear

## Specifications

* Version: 6.2.2
* Browser: Chrome , FireFox (works fine on Safari, did not test on other browsers)
* OS: Mac os

**Comment by connor-baer** [comment] 2023-02-21 16:24
Thank you so much for this report, @sirineJ! 🙌

I was able to reproduce the bug and found that the first row is hidden because it's overflowing its scrollable container. I couldn't find a quick fix, so I will look into refactoring the component to use `position: sticky` instead. I'll open a PR (or provide another update) by the end of this week.

**Comment by connor-baer** [comment] 2023-03-02 08:39
I've opened a pull request to fix the bug (#1969). Until the bugfix is merged and released, you can work around the issue by setting the `rowHeader` prop to `false` (it defaults to `true`).

**Closed** 2023-03-02 12:08 UTC
Labels: 🐞 bug
